version: "3.9"

services:
  api:
    build:
      context: .
    image: vkarpovich/skypro_hw_26
    ports:
      - 25000:25000
    networks:
      - app_net

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U flask_app" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

