name: Build and Deploy Workflow

on:
  push:
    branches:
      - main  # Можно указать ветку, на которую реагирует push

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3  # Обновление до последней стабильной версии

      - name: Build Docker image
        run: docker build -t vkarpovich/skypro_hw_26:${{ github.ref_name }}-${{ github.run_id }} .

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push vkarpovich/skypro_hw_26:${{ github.ref_name }}-${{ github.run_id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3  # Использование актуальной версии

      - name: Render configuration files
        run: |
          mkdir -p deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
          cat docker_ci_config.py | envsubst > deploy/docker_config.py

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3  # Указание более стабильной версии действия
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yaml,deploy/docker_config.py"
          target: "flask_app_ci"
          strip_components: 1

      - name: Deploy application
        uses: appleboy/ssh-action@v0.1.3  # Указание стабильной версии для SSH
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd flask_app_ci
            echo "${{ secrets.PASSWORD }}" | sudo -S docker compose up -d







